"""create initial schema

Revision ID: 26d265ec53fc
Revises: 
Create Date: 2026-03-06 16:34:59.775821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d265ec53fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surface_type', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.create_index('idx_courts_city', ['city'], unique=False)
        batch_op.create_index('idx_courts_district', ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_courts_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'completed')", name='ck_bookings_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_bookings_time_range'),
    sa.CheckConstraint('slot_count >= 2', name='ck_bookings_min_slot_count'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('idx_bookings_court_id', ['court_id'], unique=False)
        batch_op.create_index('idx_bookings_start_time', ['start_time'], unique=False)
        batch_op.create_index('idx_bookings_status', ['status'], unique=False)
        batch_op.create_index('idx_bookings_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)

    op.create_table('court_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_court_hours_time_range'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_court_hours_weekday'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'weekday', name='uq_court_hours_court_weekday')
    )
    with op.batch_alter_table('court_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_hours_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_hours_id'), ['id'], unique=False)

    op.create_table('booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'slot_start', name='uq_booking_slots_booking_slot'),
    sa.UniqueConstraint('court_id', 'slot_start', name='uq_booking_slots_court_slot')
    )
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.create_index('idx_booking_slots_booking_id', ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_slots_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_slots_id'))
        batch_op.drop_index('idx_booking_slots_booking_id')

    op.drop_table('booking_slots')
    with op.batch_alter_table('court_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_hours_id'))
        batch_op.drop_index(batch_op.f('ix_court_hours_court_id'))

    op.drop_table('court_hours')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index('idx_bookings_user_id')
        batch_op.drop_index('idx_bookings_status')
        batch_op.drop_index('idx_bookings_start_time')
        batch_op.drop_index('idx_bookings_court_id')

    op.drop_table('bookings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courts_id'))
        batch_op.drop_index('idx_courts_district')
        batch_op.drop_index('idx_courts_city')

    op.drop_table('courts')
    # ### end Alembic commands ###
